GET http://localhost:8000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXloYWlsbyIsImlhdCI6MTcyNzQ0NDAzNywiZXhwIjoxNzI3NDQ0OTM3fQ.B952cAvdP4RXGvQDs5F0I6tsUatCGmyOYg_Ja5SC7iE

###

POST http://localhost:8000/user
Content-Type: application/json

{
  "userName": "nazar",
  "email": "nazar@test.test",
  "password": "test123"
}

### 

POST http://localhost:8000/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibXloYWlsbyIsImlhdCI6MTcyNzQ0NDAzNywiZXhwIjoxNzI4NzQwMDM3fQ.Hn-9ZWbaGuziwWtnhu2YcXXJorVGcHxXsZCq-6yNDH4"
}

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
  "email": "nazar@test.test",
  "password": "test123"
}

###

DELETE http://localhost:8000/logout
Content-Type: application/json

{
  "userId": 13
}